### ISSUE TITLE
Model is not packaged with the application

### ISSUE THREAD

**Issue by fridex** [thoth-station/glyph#10]
**Describe the bug**

The model present in `data` directory is not packaged with the application. Once the application will be released on PyPI, loading the default model will fail. See setup.py configuration and it's `package_data`. The data directory should be placed within the module.

**Comment by tushar7sharma** [comment]
> **Describe the bug**
> 
> The model present in `data` directory is not packaged with the application. Once the application will be released on PyPI, loading the default model will fail. See setup.py configuration and it's `package_data`. The data directory should be placed within the module.

So the data/ directory should be in the same folder as cli.py?

**Comment by fridex** [comment]
> > **Describe the bug**
> > The model present in `data` directory is not packaged with the application. Once the application will be released on PyPI, loading the default model will fail. See setup.py configuration and it's `package_data`. The data directory should be placed within the module.
> 
> So the data/ directory should be in the same folder as cli.py?

It should be in the package directory, see:

https://github.com/thoth-station/glyph/blob/891496dfd06043e2213ba0494c0e1da1c93cd2e7/setup.py#L80

`py.typed` should be placed in `thoth/glyph/py.typed` (it is missing). In a similar way, you can move the data dir to `thoth/glyph/data/`.

**Comment by tushar7sharma** [comment]
@fridex  I've modified the package_data to include all the contents of the data folder : 
`package_data={"thoth.glyph": ["data/*"]}`

I don't know what's the use of the py.typed file, which is missing. Should I just ignore it, or is it some auto-generated file?

**Comment by fridex** [comment]
> @fridex I've modified the package_data to include all the contents of the data folder :
> `package_data={"thoth.glyph": ["data/*"]}`
> 
> I don't know what's the use of the py.typed file, which is missing. Should I just ignore it, or is it some auto-generated file?

It's used to propagate type information. See https://www.python.org/dev/peps/pep-0561/#packaging-type-information Simply create an empty file and place it in `thoth/glyph/py.typed`.
