### ISSUE TITLE
Remove load_model warning from logs

### ISSUE THREAD

**Issue by fridex** [thoth-station/glyph#37]
**Describe the question**

Each time the tool is run, I see the following warning message produced:

```
Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.
```

**To Reproduce**
1. Run  thoth-glyph on any message:

  ```
  $ thoth-glyph classify -m "Fix issue with numerical computation"
  2020-08-17 11:33:11,898 380438 WARNING  thoth.common:346: Logging to a Sentry instance is turned off
  2020-08-17 11:33:11,898 380438 INFO     thoth.common:368: Logging to rsyslog endpoint is turned off
  2020-08-17 11:33:11,899 380438 INFO     glyph:68: Version: 0.1.0
  2020-08-17 11:33:11,899 380438 INFO     glyph:83: Classifying commit
  2020-08-17 11:33:11,899 380438 INFO     thoth.glyph.models:33: Model Path : /home/fpokorny/.local/share/virtualenvs/a- 
 EouiYCWm/lib/python3.7/site-packages/thoth/glyph/data/model_commits_v2_quant.bin
  Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very 
  similar.
  Label : corrective
  ```
2. See the warning produced:

**Expected behavior**

No such warning should be present in logs.

**Comment by tushar7sharma** [comment]
> **Describe the question**
> 
> Each time the tool is run, I see the following warning message produced:
> 
> ```
> Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.
> ```
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Run  thoth-glyph on any message:
> 
> ```
> $ thoth-glyph classify -m "Fix issue with numerical computation"
> 2020-08-17 11:33:11,898 380438 WARNING  thoth.common:346: Logging to a Sentry instance is turned off
> 2020-08-17 11:33:11,898 380438 INFO     thoth.common:368: Logging to rsyslog endpoint is turned off
> 2020-08-17 11:33:11,899 380438 INFO     glyph:68: Version: 0.1.0
> 2020-08-17 11:33:11,899 380438 INFO     glyph:83: Classifying commit
> 2020-08-17 11:33:11,899 380438 INFO     thoth.glyph.models:33: Model Path : /home/fpokorny/.local/share/virtualenvs/a- 
> EouiYCWm/lib/python3.7/site-packages/thoth/glyph/data/model_commits_v2_quant.bin
> Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very 
> similar.
> Label : corrective
> ```
> 
> 1. See the warning produced:
> 
> **Expected behavior**
> 
> No such warning should be present in logs.

They have removed this warning message from future releases.
https://github.com/facebookresearch/fastText/issues/1067
